### ISSUE TITLE
vcsstate assumes LANG=en_US.UTF8

### ISSUE THREAD

**Issue by maruel** [shurcooL/vcsstate#6]
I found this problem while trying out gostatus. This breaks also your project Go-Package-Store.
## Repro

```
$ go get -u github.com/shurcooL/gostatus
$ gostatus github.com/shurcooL/gostatus
```

Running on `git version 2.9.3`, `go version go1.7.1 linux/amd64` on Ubuntu 14.04.
## Expected

States everything is up to date.
## Actual

```
$ gostatus github.com/shurcooL/gostatus
2016/09/26 10:59:38 github.com/shurcooL/gostatus: no HEAD branch
  ?  github.com/shurcooL/gostatus/...
        ? Unreachable remote (check your connection)
$ cd $GOPATH/src/github.com/shurcooL/gostatus
$ git remote -v
origin  https://github.com/shurcooL/gostatus (fetch)
origin  https://github.com/shurcooL/gostatus (push)
$ git remote show origin
* distante origin
  URL de rapatriement : https://github.com/shurcooL/gostatus
  URL push : https://github.com/shurcooL/gostatus
  Branche HEAD : master
  Branches distantes :
    experiment/offline_and_diff_flags suivi
    master                            suivi
  Branche locale configurée pour 'git pull' :
    master fusionne avec la distante master
  Référence locale configurée pour 'git push' :
    master pousse vers master (à jour)
$ echo $LANG
fr_CA.UTF-8
```
## Problem

`git.go` assumes `LANG=en_US.UTF8` and tries to parse output that is not in porcelain mode. The fix would be to force environment variable `LANG=en_US.UTF8` at line 139.

**Comment by dmitshur** [comment]
Hi, thanks for reporting this bug!

Yeah, that makes sense. Unfortunately, there are some cases where I had to fall back to using porcelain commands...

I've just pushed PR #7 that adds a new git 2.8+ specific backend. I plan to merge it soon (update: already done). It gets rid of `parseGitRemote`, for one. But it still has the `getBranch`, which is one place where this is an issue.

Would you be interested in working on a PR that fixes this issue?
